sudo: false
language: ruby
cache: bundler

notifications:
  email: false

matrix:
  fast_finish: true
  include:
    - rvm: ruby-head
      gemfile: gemfiles/railsmaster.gemfile
    - rvm: jruby-9.2.10.0
      gemfile: gemfiles/jruby.gemfile
    - rvm: 2.7
      gemfile: Gemfile
    - rvm: 2.6
      gemfile: gemfiles/rails5.gemfile
    - rvm: 2.5
      gemfile: Gemfile
    - rvm: 2.5
      gemfile: gemfiles/activerecord42.gemfile
  allow_failures:
    - rvm: ruby-head
      gemfile: gemfiles/railsmaster.gemfile
    - rvm: jruby-9.2.10.0
      gemfile: gemfiles/jruby.gemfile
